name: Deploy Vehicle Insurance Application

on:
  push:
    branches: [main]

jobs:

  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Backend Docker Image
        run: docker build -f Dockerfile.backend -t backend .

      - name: Tag Backend Image
        run: |
          docker tag backend:latest \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_BACKEND_REPO }}:latest

      - name: Push Backend Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_BACKEND_REPO }}:latest

      - name: Build Frontend Docker Image
        run: docker build -f Dockerfile.frontend -t frontend .

      - name: Tag Frontend Image
        run: |
          docker tag frontend:latest \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_FRONTEND_REPO }}:latest

      - name: Push Frontend Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_FRONTEND_REPO }}:latest


  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr           
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull latest Docker images
        run: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_BACKEND_REPO }}:latest
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_FRONTEND_REPO }}:latest

      - name: Stop existing containers
        run: docker-compose down || true

      - name: Start application containers
        run: docker-compose up -d